global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Docker container can reach host via this
    tls_config:
      insecure_skip_verify: true
